<?php
include('session.php');
include('../config.php');
 $cand_id=$_SESSION['id'];
 
  $chck=mysqli_query($conn,"select * from tbl_election");
 $count=mysqli_num_rows($chck);
 $fet=mysqli_fetch_array($chck);
  if($fet['election_status']!=1){
	  echo "<script>window.location.href='../index.php';</script>";
  }
?>
<html>
  <head>
    <title>Payment</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <style>
      html, body {
      display: flex;
      justify-content: center;
      height: 100%;
      }
      body, div, h1, input, p { 
      padding: 0;
      margin: 0;
      outline: none;
      font-family: Roboto, Arial, sans-serif;
      font-size: 16px;
      color: #666;
      }
      h1 {
      padding: 10px 0;
      font-size: 32px;
      font-weight: 300;
      text-align: center;
      }
      p {
      font-size: 12px;
      }
      hr {
      color: #a9a9a9;
      opacity: 0.3;
      }
      .main-block {
      width:100%; 
      height: auto; 
      padding: 10px 0;
      margin: auto;
      border-radius: 5px; 
      border: solid 1px #ccc;
      box-shadow: 1px 2px 5px rgba(0,0,0,.31); 
      background: #ebebeb; 
      }
      form {
      margin: 0 30px;
      }
      .account-type, .gender {
      margin: 15px 0;
      }
      input[type=radio] {
      display: none;
      }
      label#icon {
      margin: 0;
      border-radius: 5px 0 0 5px;
      }
      label.radio {
      position: relative;
      display: inline-block;
      padding-top: 4px;
      margin-right: 20px;
      text-indent: 30px;
      overflow: visible;
      cursor: pointer;
      }
      label.radio:before {
      content: "";
      position: absolute;
      top: 2px;
      left: 0;
      width: 20px;
      height: 20px;
      border-radius: 50%;
      background: #1c87c9;
      }
      label.radio:after {
      content: "";
      position: absolute;
      width: 9px;
      height: 4px;
      top: 8px;
      left: 4px;
      border: 3px solid #fff;
      border-top: none;
      border-right: none;
      transform: rotate(-45deg);
      opacity: 0;
      }
      input[type=radio]:checked + label:after {
      opacity: 1;
      }
      input[type=text], input[type=password] {
      width: calc(100% - 57px);
      height: 36px;
      margin: 13px 0 0 -5px;
      padding-left: 10px; 
      border-radius: 0 5px 5px 0;
      border: solid 1px #cbc9c9; 
      box-shadow: 1px 2px 5px rgba(0,0,0,.09); 
      background: #fff; 
      }
      input[type=password] {
      margin-bottom: 15px;
      }
      #icon {
      display: inline-block;
      padding: 9.3px 15px;
      box-shadow: 1px 2px 5px rgba(0,0,0,.09); 
      background: #1c87c9;
      color: #fff;
      text-align: center;
      }
      .btn-block {
      margin-top: 10px;
      text-align: center;
      }
      
    </style>
  </head>
  <body>
  <?php
  $cand_id=$_SESSION['id'];
 $pay=mysqli_query($conn,"select payment from tbl_candidate where login_id='$cand_id'");
 $payfet=mysqli_fetch_array($pay);
 if($payfet['payment']==50000){
	                header('Location:index.php');
 } else{?>
   
		  <div class="main-block" style="background:transparent;">
 <?php } 
 $apiKey="rzp_test_K3E3DlW6vk6dP1";
               $x=50000;
			   ?>
	  
			   <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
			   <form action="payment_act.php" method="POST">
			    <h1>Payment</h1>
       
        <div class="btn-block">
          <p>By clicking the above box, you agree on our <a href="">Election Payment Policy</a>.</p>
          <input type="hidden" custom="Hidden Element" name="hidden" class="btn btn-primary">
		  
        </div>
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $x * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="order_CgmcjRh9ti2lP7"// Replace with the order_id generated by you in the backend.
    data-buttontext="Proceed"
    data-name="OVS 2022 Payment portal"
    data-description="Everything’s better with a bit of fragrance."
    data-image="https://img.freepik.com/free-photo/online-payment-security-concept-3d-phone-bill_107791-16722.jpg?size=626&ext=jpg&ga=GA1.1.2105213239.1669963815&semt=ais"
    data-prefill.name="OVS"
    data-prefill.email=""
    data-theme.color="blue"
>
</script>


      
</form>
<style>
    .razorpay-payment-button{
       width: 100%;
      padding: 10px 0;
      margin: 10px auto;
      border-radius: 5px; 
      border: none;
      background: #1c87c9; 
      font-size: 14px;
      font-weight: 600;
      color: #fff;
    }
</style>

</div>
  </body>
</html>